"""incidents and audit_log tables

Revision ID: e05b7a4d79f7
Revises:
Create Date: 2026-08-11 00:52:19.712484

Hand-written, not autogenerated: no local Postgres was reachable to run
`alembic revision --autogenerate` against (see CLAUDE.md — Docker Desktop
not installed yet). Columns/constraints mirror app.models.incident and
app.models.audit exactly. Verify with `alembic upgrade head` once a DB
is available, before this migration is trusted.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e05b7a4d79f7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

INCIDENT_SOURCE = sa.Enum(
    "github_actions",
    "api_health",
    "app_logs",
    "docker",
    "database",
    name="incident_source",
)
INCIDENT_STATE = sa.Enum(
    "detected",
    "triaging",
    "investigating",
    "diagnosing",
    "needs_human_triage",
    "fix_proposed",
    "verifying",
    "escalated",
    "awaiting_approval",
    "approved",
    "rejected",
    "merged",
    "closed",
    name="incident_state",
)


def upgrade() -> None:
    op.create_table(
        "incidents",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("source", INCIDENT_SOURCE, nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("state", INCIDENT_STATE, nullable=False, server_default="detected"),
        sa.Column("raw_payload", postgresql.JSONB(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.UniqueConstraint("source", "external_id", name="uq_incidents_source_external_id"),
    )

    op.create_table(
        "audit_log",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "incident_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("incidents.id"),
            nullable=False,
        ),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column(
            "detail", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )


def downgrade() -> None:
    op.drop_table("audit_log")
    op.drop_table("incidents")
    # drop_table does not remove Postgres enum types — they must go explicitly,
    # and only after both tables (their only users) are gone.
    INCIDENT_STATE.drop(op.get_bind(), checkfirst=True)
    INCIDENT_SOURCE.drop(op.get_bind(), checkfirst=True)
